### ISSUE TITLE
Thanks a lot for making this, I have an issue with block time

### ISSUE THREAD

**Issue by dangershony** [nbd-wtf/bitcoin_signet#4]
Just specifying block interval as 60 seconds doesn't enforce that and I get random times close to 5 min between blocks
Any recommendations how to get it to 1min blocks?

**Comment by rsafier** [comment]
> Just specifying block interval as 60 seconds doesn't enforce that and I get random times close to 5 min between blocks Any recommendations how to get it to 1min blocks?

You need to run the mutiny-net fork with adjustments to `bitcoind` if you need proper control over the block-time production, otherwise Bitcoin Core will end up adjusting difficulty back towards the 10 minute standard.
